name: Deploy to EC2 (master)

on:
  push:
    branches: [ master ]
  workflow_dispatch: {}

jobs:
  deploy:
    # If using environment-scoped secrets, uncomment the line below:
    # environment: production
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      - name: Preflight: Check required secrets
        # Use '::error::' for clear failure messages in the GitHub UI
        run: | 
          echo "Checking for required secrets..."
          test -n "${{ secrets.EC2_HOST }}" || { echo "::error::Missing secret EC2_HOST. Deployment stopped."; exit 1; }
          test -n "${{ secrets.EC2_USER }}" || { echo "::error::Missing secret EC2_USER. Deployment stopped."; exit 1; }
          test -n "${{ secrets.SSH_PRIVATE_KEY }}" || { echo "::error::Missing secret SSH_PRIVATE_KEY. Deployment stopped."; exit 1; }
          echo "All secrets present."

      - name: Add EC2 host key to known_hosts
        run: |
          mkdir -p ~/.ssh
          # Use -T 5 to set a 5-second timeout for ssh-keyscan
          ssh-keyscan -T 5 -H "${{ secrets.EC2_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy via SSH and Run Remote Script
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # Set a generous timeout for the connection
          timeout: 60s 
          
          # The remote script to run on the EC2 server
          script: |
            # Set options for robust shell scripting
            set -euo pipefail 
            
            # Navigate to the application directory
            cd /opt/CelestialAi_app/
            
            # Execute the deployment script on the EC2 instance
            bash ./deploy.sh
            
            echo "Remote deployment script finished successfully."
