name: Deploy to EC2 (master)

on:
  push:
    branches: [ master ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    # add this if your secrets are Environment-scoped:
    # environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Preflight: required secrets
        run: |
          test -n "${{ secrets.EC2_HOST }}" || { echo "Missing secret EC2_HOST"; exit 1; }
          test -n "${{ secrets.EC2_USER }}" || { echo "Missing secret EC2_USER"; exit 1; }
          test -n "${{ secrets.SSH_PRIVATE_KEY }}" || { echo "Missing secret SSH_PRIVATE_KEY"; exit 1; }

      - name: Add EC2 host key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -T 5 -H "${{ secrets.EC2_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -euo pipefail
            bash /opt/CelestialAi_app/deploy.sh
